### ISSUE TITLE
Movimentos rápidos as vezes matam a cobra

### ISSUE THREAD

**Issue by andrevantunes** [RicardoFredes/snake-game#1]
As vezes quando está indo em uma direção (exemplo pra direita) e move rapidamente 2 vezes (exemplo cima e esquerda), dá game over :-(

**Comment by RicardoFredes** [comment]
Obrigado pelo report @AndreAntunesVieira , essa Issue foi resolvida no commit https://github.com/RicardoFredes/snake-game/commit/cb0d17aee135c53f8bab5ab72a53aa44f48f2930
